name: Security Scans

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  security:
    uses: TheDataEngineX/.github/.github/workflows/security.yml@main
    secrets: inherit
