"""Foundation layer — the domain model as pure types.

Per §5.5 the dependency arrows all point inward::

    interfaces -> application -> foundation <- runtime, providers

This package therefore imports the standard library and Pydantic and nothing
else. No frameworks, no providers, no I/O, no global mutable domain state. The
architecture tests in ``tests/architecture/`` enforce that mechanically; the
rule is stated here because a layer that quietly grows a dependency stops being
a foundation.

Concrete providers are wired only in ``bootstrap/``.
"""

from dataenginex.foundation.artifacts import (
    Artifact,
    ArtifactDescriptor,
    ArtifactReference,
    Digest,
    DigestAlgorithm,
    RetentionState,
    digest_bytes,
    digest_stream,
)
from dataenginex.foundation.contracts import (
    ArtifactStore,
    BackendCapabilities,
    EstimateContext,
    ExecutionBackend,
    ExecutionContext,
    ExecutionPlan,
    ExecutionResult,
    PolicyEngine,
    ResourceRepository,
    SecretLease,
    SecretProvider,
)
from dataenginex.foundation.events import (
    AuditEvent,
    AuditEventType,
    EventEnvelope,
    LineageEdge,
    LineageNodeType,
    LineageRelation,
    MetadataEvent,
)
from dataenginex.foundation.identity import (
    CapabilityToken,
    Principal,
    PrincipalType,
    SecretReference,
    TrustLevel,
    issue_capability,
)
from dataenginex.foundation.ids import (
    ArtifactId,
    AttemptId,
    InstallationId,
    PolicyDecisionId,
    PrincipalId,
    ProjectId,
    ResourceId,
    RevisionId,
    RunId,
    WorkspaceId,
    new_id,
    uuid7,
)
from dataenginex.foundation.invariants import (
    InvariantViolation,
    check_active_revision_published,
    check_artifacts_not_overwritten,
    check_attempt_belongs_to_run,
    check_cross_project_access_granted,
    check_external_action_authorized,
    check_invariants,
    check_revision_no_secrets,
    check_run_pins_published_revision,
    check_source_deletion_impact,
    check_worker_scope_minimal,
)
from dataenginex.foundation.operations import (
    Determinism,
    IdempotencyStrategy,
    IOContract,
    Operation,
    ResourceEstimate,
    ResourceRequest,
    RiskLevel,
    SideEffectClass,
)
from dataenginex.foundation.operations_catalog import (
    BUILTIN_OPERATIONS,
    OperationRegistry,
    UnknownOperationError,
    registry,
)
from dataenginex.foundation.policy import (
    Approval,
    ApprovalState,
    AuthorizationRequest,
    NetworkDestination,
    Obligation,
    ObligationType,
    Policy,
    PolicyDecision,
    PolicyEffect,
    extract_host,
)
from dataenginex.foundation.projects import (
    FrozenModel,
    Installation,
    Project,
    ProjectRevision,
    PublicationStatus,
    RevisionFile,
    ValidationIssue,
    ValidationReport,
    ValidationSeverity,
    utcnow,
)
from dataenginex.foundation.resources import (
    Classification,
    DataFacet,
    LifecycleState,
    ModelFacet,
    PromptFacet,
    Resource,
    ResourceQuery,
    ResourceType,
    SensitivityFacet,
)
from dataenginex.foundation.secrets import (
    SecretReferenceV2,
    SecretRotationPolicy,
)
from dataenginex.foundation.workloads import (
    AttemptState,
    ExecutionAttempt,
    InteractiveRequest,
    InteractiveResult,
    ObservedResources,
    RunState,
    ServiceState,
    TriggerType,
    WorkloadDefinition,
    WorkloadKind,
    WorkloadRun,
    can_service_transition,
    can_transition,
    is_service_terminal,
    is_terminal,
    priority_for,
)
from dataenginex.foundation.workspaces import (
    Workspace,
    WorkspaceMember,
    WorkspaceMemberRole,
)

__all__ = [
    "priority_for",
    "Approval",
    "ApprovalState",
    "Artifact",
    "ArtifactDescriptor",
    "ArtifactId",
    "ArtifactReference",
    "ArtifactStore",
    "AttemptId",
    "AttemptState",
    "AuditEvent",
    "AuditEventType",
    "AuthorizationRequest",
    "BUILTIN_OPERATIONS",
    "BackendCapabilities",
    "CapabilityToken",
    "Classification",
    "DataFacet",
    "Determinism",
    "Digest",
    "DigestAlgorithm",
    "EstimateContext",
    "EventEnvelope",
    "ExecutionAttempt",
    "ExecutionBackend",
    "InteractiveRequest",
    "InteractiveResult",
    "ExecutionContext",
    "ExecutionPlan",
    "ExecutionResult",
    "FrozenModel",
    "IOContract",
    "IdempotencyStrategy",
    "Installation",
    "InstallationId",
    "InvariantViolation",
    "LifecycleState",
    "LineageEdge",
    "LineageNodeType",
    "LineageRelation",
    "MetadataEvent",
    "ModelFacet",
    "NetworkDestination",
    "Obligation",
    "ObligationType",
    "ObservedResources",
    "Operation",
    "OperationRegistry",
    "Policy",
    "PolicyDecision",
    "PolicyDecisionId",
    "PolicyEffect",
    "PolicyEngine",
    "Principal",
    "PrincipalId",
    "PrincipalType",
    "Project",
    "ProjectId",
    "ProjectRevision",
    "PromptFacet",
    "PublicationStatus",
    "Resource",
    "ResourceEstimate",
    "ResourceId",
    "ResourceQuery",
    "ResourceRepository",
    "ResourceRequest",
    "ResourceType",
    "RetentionState",
    "RevisionFile",
    "RevisionId",
    "RiskLevel",
    "RunId",
    "RunState",
    "SecretLease",
    "SecretProvider",
    "SecretReference",
    "SecretReferenceV2",
    "SecretRotationPolicy",
    "SensitivityFacet",
    "ServiceState",
    "SideEffectClass",
    "TriggerType",
    "TrustLevel",
    "UnknownOperationError",
    "ValidationIssue",
    "ValidationReport",
    "ValidationSeverity",
    "WorkloadDefinition",
    "WorkloadKind",
    "WorkloadRun",
    "Workspace",
    "WorkspaceId",
    "WorkspaceMember",
    "WorkspaceMemberRole",
    "can_service_transition",
    "can_transition",
    "check_active_revision_published",
    "check_artifacts_not_overwritten",
    "check_attempt_belongs_to_run",
    "check_cross_project_access_granted",
    "check_external_action_authorized",
    "check_invariants",
    "check_revision_no_secrets",
    "check_run_pins_published_revision",
    "check_source_deletion_impact",
    "check_worker_scope_minimal",
    "digest_bytes",
    "digest_stream",
    "extract_host",
    "is_service_terminal",
    "is_terminal",
    "issue_capability",
    "new_id",
    "registry",
    "utcnow",
    "uuid7",
]
